services:
  - type: web
    name: Private-Chat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn base:app --bind 0.0.0.0:10000
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11